---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  - file el9/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  - file el9/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  - file el9/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  - file el9/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el8 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el8 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el8
  - file el8/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el8 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el8 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el8
  - file el8/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el8 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el8 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el8
  - file el8/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el8 s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el8 s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el8
  - file el8/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el7 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el7 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el7
  - file el7/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el7 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el7 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el7
  - file el7/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: amzn2 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh amzn2 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la amzn2
  - file amzn2/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: amzn2 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh amzn2 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la amzn2
  - file amzn2/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc37 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc37 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc37
  - file fc37/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc37 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc37 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc37
  - file fc37/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc37 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc37 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc37
  - file fc37/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc37 s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc37 s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc37
  - file fc37/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  - file fc36/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  - file fc36/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  - file fc36/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  - file fc36/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc35
  - file fc35/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc35
  - file fc35/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc35
  - file fc35/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc35 s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc35 s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc35
  - file fc35/zerotier-one
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
